### ISSUE TITLE
Remove .gitignore from project root

### ISSUE THREAD

**Issue by acabal** [drgrigg/h-beam-piper_cosmic_computer#1]

**Comment by drgrigg** [comment]
I take it this means you want the \dist directory included in the repository on GitHub? Or should \dist be moved out of the root?

**Comment by drgrigg** [comment]
I'm assuming the latter and deleting /dist (it will be re-created on next build).

Done.

**Comment by acabal** [comment]
Yes, `./dist/` should not be in the repo.  Are you using an older version of the tools?  `build` hasn't created `./dist/` in quite some time, instead it builds into the CWD or a target folder you specify via a flag.

**Comment by drgrigg** [comment]
I was using the tools I downloaded on Jun 22, 2017 (which I've since updated as per your comment on LICENSE.md) and the following example command line in your "Producing an Ebook" page:

~/tools/build --output-dir="dist" --kindle --check .

I figure if I use --output-dir="~/Documents/dist" or similar then all will be well?
